image: node:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: ci_db
  POSTGRES_USER: ci_user
  POSTGRES_PASSWORD: ""

cache:
  paths:
    - node_modules/
    - examples/simple/node_modules/
    - examples/postgres/node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    # lib
    - yarn
    - yarn build
    # simple example
    - yarn --cwd examples/simple
    # postgres example
    - yarn --cwd examples/postgres
    # lint all
    - yarn lint

# lib
test:
  stage: test
  script:
    - yarn test

# simple example
test:simple:
  stage: test
  script:
    - yarn build # need lib
    - yarn --cwd examples/simple test

# postgres example
test:postgres:
  stage: test
  script:
    - yarn build # need lib
    - yarn --cwd examples/postgres test
