image: node:latest

cache:
  paths:
    - node_modules/
    - examples/simple/node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    # lib
    - yarn
    - yarn build
    # examples
    - yarn --cwd examples/simple
    # lint all
    - yarn lint

# lib
test:
  stage: test
  script:
    - yarn test

# simple example
test:examples:
  stage: test
  script:
    - yarn build # need lib
    - yarn --cwd examples/simple test
