image: node:latest

cache:
  paths:
  - node_modules/
  - examples/simple/node_modules/

test:main:
  script:
   - yarn
   - yarn test

test:examples:
  script:
  - yarn --cwd examples/simple
  - yarn --cwd examples/simple test
