image: node:latest

services:
  - postgres:latest
  - mongo:latest

variables:
  POSTGRES_DB: ci_db
  POSTGRES_USER: ci_user
  POSTGRES_PASSWORD: ""
  TEST_DB_URL: mongodb://mongo:27017/test

cache:
  paths:
    - node_modules/
    - examples/mongo/node_modules/
    - examples/postgres/node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    # lib
    - yarn
    - yarn build
    # mongo example
    - yarn --cwd examples/mongo
    # postgres example
    - yarn --cwd examples/postgres
    # lint all
    - yarn lint

# lib
test:
  stage: test
  script:
    - yarn test

# mongo example
test:mongo:
  stage: test
  script:
    - yarn build # need lib
    - yarn --cwd examples/mongo test

# postgres example
test:postgres:
  stage: test
  script:
    - yarn build # need lib
    - yarn --cwd examples/postgres test
